language: node_js
addons:
  mariadb: '10.5'
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js: '14'
before_script:
- npm run compile
- sudo mysql -e "CREATE USER 'cotizacionesBrou'@'localhost' IDENTIFIED BY 'cotizacionesBrou';"
- sudo mysql -e "GRANT ALL ON cotizacionesBrou.* TO 'cotizacionesBrou'@'localhost';"
- sudo mysql -e "CREATE DATABASE IF NOT EXISTS cotizacionesBrou;"
- npm run migrate-up
- npm run seed
- npm run test
deploy:
  provider: heroku
  api_key:
    # This is ok, it's encrypted ;)
    secure: P/qv3qye2QOcDgo/uvo+mY5vmeFN4dcqbd3pL9pEXD7z3RwdE3uW+gcchI9Fj3KXr2QTWqNS79gO0pwF2hN/cRB1NBC0jNbH0I4WIHOeD/UCH7nDahJvd8dBuTYfGCtuX9OZi9ybHymeZeetV/TU8Tyuq0rbzdaP3BU37k0CScZ+/T+Y2wUzrcS13lobJGgIf+L2eLOkq5cmUcJHtZXl0YaocksyEPm3CTb0WikzGM9LxJlrlqmmGnqMICpZ/gSFjFBVyeRKpJ+mn9Qg1QJglBavetsWdVQ67/9OFlsMbUvmkAHYS1o6BBhoLgF3GZ5+GyNNldoHzr2zENqZjWrxhEKUF9ox5BoIq+UPzBT0c+QZqIwbSa9NXa65EC9a0IGi80C9VYBv4GtFaR+TdO9/4TwyUsntNXL5Rl1GbaxMPMsgFt4OS7YY83eoUK6AKV+AkCS29c6q8iWbXXs2EB2zRhobp1oL07xIfBZvvbq/pGtWey4AT37iGx3B3juY5aaVND6u0+O0bqHxNW1nV44Y5YmsrjaUN8aERel0JNFvRiTxCc1eqclW9CfYGacfU61Gs2XsnCzF2UEsMTEWiLUVrBxvTdb0jw8GpBCPxVqVsMmwapVGk6pB2/sLwa0S4gMFfpMHGcQ70fdmMe0O1ZnqGB72hv6sapSZlMfQOil+LLg=
  app: cotizaciones-brou
